GO ?= go
GOLANGCI_LINT ?= golangci-lint

.PHONY: test test-backends test-mysql lint vet bench

test:
	$(GO) test ./...
	$(MAKE) test-backends

test-backends:
	cd mongo && GOWORK=off $(GO) test ./...
	cd postgres && GOWORK=off $(GO) test ./...
	cd redis && GOWORK=off $(GO) test ./...

test-mysql:
	cd mysql && GOWORK=off $(GO) test ./...

lint:
	$(GOLANGCI_LINT) run ./... ./mysql/... ./mongo/... ./postgres/... ./redis/...

vet:
	$(GO) vet ./... ./mysql/... ./mongo/... ./postgres/... ./redis/...

bench:
	cd mongo && GOWORK=off $(GO) test -bench=. -benchmem ./...
	cd postgres && GOWORK=off $(GO) test -bench=. -benchmem ./...
	cd redis && GOWORK=off $(GO) test -bench=. -benchmem ./...
	cd mysql && GOWORK=off $(GO) test -bench=. -benchmem ./...
