GO ?= go
GOLANGCI_LINT ?= golangci-lint

.PHONY: test test-backends test-mysql integration-mysql lint vet bench

test:
	$(GO) test -short ./...
	$(MAKE) test-backends

test-backends:
	cd mysql && GOWORK=off $(GO) test -short ./...
	cd mongo && GOWORK=off $(GO) test -short ./...
	cd postgres && GOWORK=off $(GO) test -short ./...
	cd redis && GOWORK=off $(GO) test -short ./...

test-mysql:
	cd mysql && GOWORK=off $(GO) test -short ./...

integration-mysql:
	./mysql/test/testdata/generate_mysql_binlog.sh mysql:8.4
	cd mysql && GOWORK=off $(GO) test ./...

lint:
	$(GOLANGCI_LINT) run ./... ./mysql/... ./mongo/... ./postgres/... ./redis/...

vet:
	$(GO) vet ./... ./mysql/... ./mongo/... ./postgres/... ./redis/...

bench:
	cd mongo && GOWORK=off $(GO) test -bench=. -benchmem ./...
	cd postgres && GOWORK=off $(GO) test -bench=. -benchmem ./...
	cd redis && GOWORK=off $(GO) test -bench=. -benchmem ./...
	cd mysql && GOWORK=off $(GO) test -bench=. -benchmem ./...
