GO ?= go
GOLANGCI_LINT ?= golangci-lint

.PHONY: test test-backends test-mysql integration integration-mysql integration-mongo integration-postgres integration-redis lint vet bench

test:
	$(GO) test -short ./...
	$(MAKE) test-backends

test-backends:
	cd mysql && GOWORK=off $(GO) test -short ./...
	cd mongo && GOWORK=off $(GO) test -short ./...
	cd postgres && GOWORK=off $(GO) test -short ./...
	cd redis && GOWORK=off $(GO) test -short ./...

test-mysql:
	cd mysql && GOWORK=off $(GO) test -short ./...

integration-mysql:
	./mysql/test/testdata/generate_mysql_binlog.sh mysql:8.4
	cd mysql && GOWORK=off $(GO) test ./...

integration: integration-mysql integration-mongo integration-postgres integration-redis

integration-mongo:
	./mongo/testdata/generate_mongo_oplog.sh mongo:7.0
	cd mongo && GOWORK=off $(GO) test ./...

integration-postgres:
	./postgres/testdata/generate_postgres_logical.sh postgres:16
	cd postgres && GOWORK=off $(GO) test ./...

integration-redis:
	./redis/testdata/generate_redis_aof.sh redis:7.2
	cd redis && GOWORK=off $(GO) test ./...

lint:
	$(GOLANGCI_LINT) run ./... ./mysql/... ./mongo/... ./postgres/... ./redis/...

vet:
	$(GO) vet ./... ./mysql/... ./mongo/... ./postgres/... ./redis/...

bench:
	cd mongo && GOWORK=off $(GO) test -bench=. -benchmem ./...
	cd postgres && GOWORK=off $(GO) test -bench=. -benchmem ./...
	cd redis && GOWORK=off $(GO) test -bench=. -benchmem ./...
	cd mysql && GOWORK=off $(GO) test -bench=. -benchmem ./...
